export const ENUM = {
  COLLECTIONS: {
    USER: 'users',
    USER_SESSION: 'userSessions',
    ORDERS: 'orders',
    PAYMENTS: 'payments',
  },

  USER_PROFILE_STATUS: {
    PENDING: 1,
    ACTIVE: 2,
    BLOCKED: 3,
    DELETED: 4,
  },

  STATUS: {
    ACTIVE: 1,
    INACTIVE: 2,
    BLOCKED: 3,
    DELETED: 4,
  },

  ENVIRONMENT: {
    DEVELOPMENT: 'dev',
    PRODUCTION: 'prod',
  },

  PLATFORM: {
    WEB: 1,
    ANDROID: 2,
    IOS: 3,
  },

  BOOKING_TYPE: {
    SCHEDULE: 1,
    INSTANT: 2,
  },

  BOOKING_ACTION: {
    ACCEPT: 1,
    REJECT: 2,
  },

  GENDER: {
    MALE: 1,
    FEMALE: 2,
    OTHER: 3,
  },

  PROFILE_TYPE: {
    CLIENT: 1,
    VENDOR: 2,
  },

  VERIFICATION_STATUS: {
    PENDING: 1,
    VERIFIED: 2,
    REJECTED: 7,
  },

  BOOKING_ACTION_ON_SHOOT_COMPLETION: {
    ACCEPT_WITH_OVERTIME: 1,
    ACCEPT_WITHOUT_OVERTIME: 2,
    REJECT: 3,
  },

  BOOKING_STATUS: {
    AUTHORIZATION_PENDING: 1,
    AUTHORIZED: 2,
    CLIENT_CANCEL: 3,
    VENDOR_REJECT: 4,
    VENDOR_NO_ACTION: 5,
    VENDOR_ACCEPTED: 6,
    STRIPE_CHARGE_COMPLETED: 7,
    VENDOR_CONFLICT_REJECTED: 8,
    SHOOT_CONFIRMATION_REQUESTED: 9,
    SHOOT_CONFIRMATION_ACCEPT: 10,
    SHOOT_CONFIRMATION_REJECTED: 11,
    STRIPE_PAYMENT_COMPLETED: 12,
    DENIED: 13,
    OVERTIME_REQUESTED: 14,
    OVERTIME_ACCEPTED: 15,
    OVERTIME_REJECTED: 16,
    STRIPE_OVERTIME_PAID: 17,
    COMPLETED: 18,
    REFUND_INITIATED: 19,
    REFUND_COMPLETED: 20,
    REFUND_FAILED: 21,
    ADDON_REQUESTED: 22,
    ADDON_ACCEPTED: 23,
    ADDON_REJECTED: 24,
    STRIPE_ADDON_PAID: 25,
    RE_SCHEDULE_REQUEST: 26,
    RE_SCHEDULE_ACCEPTED: 27,
    RE_SCHEDULE_REJECTED: 28,
    TIP_ADDED: 29,
    STRIPE_TIP_PAID: 30,
    EDIT_PHOTO_REQUESTED: 31,
    EDIT_PHOTO_ACCEPTED: 32,
    EDIT_PHOTO_REJECTED: 33,
    ONGOING: 34,
    CLIENT_CANCEL_BOOKING_INITIATED: 35,
    CLIENT_CANCEL_BOOKING_COMPLETED: 36,
    VENDOR_CANCEL_BOOKING_INITIATED: 37,
    VENDOR_CANCEL_BOOKING_COMPLETED: 38,
  },
  REFUND_STATUS: {
    REFUND_INITIATED: 19,
    REFUND_COMPLETED: 20,
    REFUND_FAILED: 21,
  },

  PAYMENT_STATUS: {
    PENDING: 1,
    SUCCESS: 2,
    FAILED: 3,
  },

  TRANSACTION_STATUS: {
    HOLD: 1,
    HOLD_AUTHORIZE: 2,
    HOLD_RELEASE: 3,
    HOLD_CAPTURING: 4,
    HOLD_CAPTURED: 5,
  },

  STRIPE_IDENTITY_WEBHOOK_STATUS: {
    CANCELED: 'canceled', // -> this is when user cancel or clicked back button
    CREATED: 'created', // -> this is when user started verification and have yet not cancel or uploaded anything
    PROCESSING: 'processing', // -> User have uploaded the document but pending at stripe
    REDACTED: 'redacted', // -> Stripe have rejected the document
    REQUIRED_INPUT: 'requires_input', // -> Stripe is still loading the UI
    VERIFIED: 'verified', // -> Stripe have verified the document.
  },

  STRIPE_IDENTITY: {
    CANCELED: 'canceled',
    CREATED: 'created',
    PROCESSING: 'processing',
    REDACTED: 'redacted',
    REQUIRED_INPUT: 'requires_input',
    VERIFIED: 'verified',
  },

  BOOKING_REQUEST_STATUS: {
    NO_REQUEST: 1,
    PENDING: 1,
    APPROVED: 3,
    REJECTED: 4,
    AUTO_CANCELED: 5,
    SELF_CANCELED: 6,
  },

  BOOKING_OTHER_STATUS: {
    NO_REQUEST: 1,
    REQUESTED: 2,
    APPROVED: 3,
    REJECTED: 4,
    AUTO_CANCELED: 5,
    SELF_CANCELED: 6,
    STRIPE_INITIATED: 7,
    STRIPE_COMPLETED: 8,
    STRIPE_FAILED: 9,
  },

  BOOKING_REQUEST_BY: {
    CLIENT: 1,
    VENDOR: 2,
  },

  BOOKING_REQUEST_TYPE: {
    RESCHEDULE_REQUEST: 1,
    CHANGE_LOCATION_REQUEST: 2,
    ADD_ON_REQUEST: 3,
    EDIT_REQUEST: 4,
    SHOOT_CONFIRMATION: 5,
  },

  PAYMENT_TYPE: {
    BOOKING: 1,
    REFUND: 2,
  },

  TRANSACTION_TYPE: {
    BOOKING: 1,
    ADD_ON: 2,
    ADDITIONAL_EDIT: 3,
    SHOOT_COMPLETION: 4,
    VENDOR_PENALTY: 5,
    CLIENT_REFUND: 6,
    VENDOR_PAYOUT: 7,
    VENDOR_REFERRAL: 8,
    CLIENT_REFERRAL: 9,
    CROSS_REFERRAL: 10,
    OFFER: 11,
    VENDOR_PENALTY_REDUCE: 12,
  },
};
export const BOOKING_COMPLETED = [
  ENUM.BOOKING_STATUS.SHOOT_CONFIRMATION_REQUESTED,
  ENUM.BOOKING_STATUS.SHOOT_CONFIRMATION_ACCEPT,
  ENUM.BOOKING_STATUS.SHOOT_CONFIRMATION_REJECTED,
  ENUM.BOOKING_STATUS.STRIPE_PAYMENT_COMPLETED,
  ENUM.BOOKING_STATUS.DENIED,
  ENUM.BOOKING_STATUS.OVERTIME_REQUESTED,
  ENUM.BOOKING_STATUS.OVERTIME_ACCEPTED,
  ENUM.BOOKING_STATUS.OVERTIME_REJECTED,
  ENUM.BOOKING_STATUS.STRIPE_OVERTIME_PAID,
  ENUM.BOOKING_STATUS.COMPLETED,
  ENUM.BOOKING_STATUS.REFUND_INITIATED,
  ENUM.BOOKING_STATUS.REFUND_COMPLETED,
  ENUM.BOOKING_STATUS.REFUND_FAILED,
  // ENUM.BOOKING_STATUS.ADDON_REQUESTED,
  // ENUM.BOOKING_STATUS.ADDON_ACCEPTED,
  // ENUM.BOOKING_STATUS.ADDON_REJECTED,
  // ENUM.BOOKING_STATUS.STRIPE_ADDON_PAID,
  // ENUM.BOOKING_STATUS.RE_SCHEDULE_REQUEST,
  // ENUM.BOOKING_STATUS.RE_SCHEDULE_ACCEPTED,
  // ENUM.BOOKING_STATUS.RE_SCHEDULE_REJECTED,
  ENUM.BOOKING_STATUS.TIP_ADDED,
  ENUM.BOOKING_STATUS.STRIPE_TIP_PAID,
  ENUM.BOOKING_STATUS.TIP_ADDED,
  ENUM.BOOKING_STATUS.STRIPE_TIP_PAID,
  ENUM.BOOKING_STATUS.EDIT_PHOTO_REQUESTED,
  ENUM.BOOKING_STATUS.EDIT_PHOTO_ACCEPTED,
  ENUM.BOOKING_STATUS.EDIT_PHOTO_REJECTED,
  ENUM.BOOKING_STATUS.ONGOING,
  ENUM.BOOKING_STATUS.CLIENT_CANCEL_BOOKING_INITIATED,
  ENUM.BOOKING_STATUS.CLIENT_CANCEL_BOOKING_COMPLETED,
  ENUM.BOOKING_STATUS.VENDOR_CANCEL_BOOKING_INITIATED,
  ENUM.BOOKING_STATUS.VENDOR_CANCEL_BOOKING_COMPLETED,
];
